defaults:
  - data: droid

resume_training: False
checkpoint_path: None

model:
  action_encoder:
    action_dim: 7
    hidden_dim: 512
    num_heads: 8
    num_layers: 8
    dropout_rate: 0.1
    projection_dim: 768
    max_sequence_length: 1024
  language_encoder:
    model_name: "openai/clip-vit-large-patch14"

training:
  learning_rate: 1e-4
  weight_decay: 0.01

trainer:
  default_root_dir: "./runs"
  fast_dev_run: False
  log_every_n_steps: 1
  max_epochs: 30
  gradient_clip_val: 1.0
  val_check_interval: 1.0

logger:
  project: "CLAP"
  save_dir: "./runs"
  name: "test"

dataloader: 
  batch_size: 16
  validate: False
  validation_percentage: 0.2
